<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function yse_style_options_extras_help($route_name, RouteMatchInterface $route_match) {
  if ($route_name == 'help.page.yse_style_options_extras') {
    $text = file_get_contents(__DIR__ . '/README.md');
    if (!Drupal::moduleHandler()->moduleExists('markdown')) {
      return '<pre>' . $text . '</pre>';
    }
    else {
      /** @var \Drupal\markdown\PluginManager\ParserManagerInterface $parser_manager */
      $parser_manager = \Drupal::service('plugin.manager.markdown.parser');
      $parser = $parser_manager->getDefaultParser([
        'render_strategy' => ['type' => 'none'],
      ]);
      return $parser->parse($text);
    }
  }
  return NULL;
}

/**
 * Implements hook_paragraphs_behavior_info_alter()
 *
 * Extends the default style options behavior with our own. This adds
 * a YAML field to the paragraph type form to store local style config.
 */

function yse_style_options_extras_paragraphs_behavior_info_alter(&$paragraphs_behavior) {
  $paragraphs_behavior['style_options']['class'] = '\Drupal\yse_style_options_extras\Plugin\paragraphs\Behavior\StyleOptionsExtrasBehavior';
}

