<?php

use Drupal\Core\Render\BubbleableMetadata;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Component\Utility\Html;

/**
 * Implements hook_help().
 */
function yse_style_options_extras_help($route_name, RouteMatchInterface $route_match) {
  if ($route_name == 'help.page.yse_style_options_extras') {
    $text = file_get_contents(__DIR__ . '/README.md');
    if (!Drupal::moduleHandler()->moduleExists('markdown')) {
      return '<pre>' . $text . '</pre>';
    }
    else {
      /** @var \Drupal\markdown\PluginManager\ParserManagerInterface $parser_manager */
      $parser_manager = \Drupal::service('plugin.manager.markdown.parser');
      $parser = $parser_manager->getDefaultParser([
        'render_strategy' => ['type' => 'none'],
      ]);
      return $parser->parse($text);
    }
  }
  return NULL;
}

use Drupal\menu_link_content\MenuLinkContentInterface;

function yse_style_options_extras_menu_link_content_presave(MenuLinkContentInterface $menu_link) {
  \Drupal::messenger()->addStatus(t('Yep %y .', ['%y' => $menu_link->title->value ]));
}
